package fr.neatmonster.nocheatplus.hooks.violationfrequency;

import fr.neatmonster.nocheatplus.config.ConfPaths;
import fr.neatmonster.nocheatplus.config.ConfigFile;

/**
 * Configuration for the ViolationFrequencyHook.
 *
 * @author xaw3ep
 *
 */

public class ViolationFrequencyConfig {
    /** Set this hook active or not */
    protected final boolean active;

    /** Log whenever more vls is added */
    protected final boolean debug;

    /** Set the want to add vl to check which generate too small vls */
    protected final int morevls;

    /** Moves count from last violated move */
    protected final int movecount;

    /** Minimum vls generated by check not need to add more vls */
    protected final int minaddedvls;

    /** Maximum total vls to stop active this hook */
    protected final int maxtotalvls;

    public ViolationFrequencyConfig(ConfigFile config) {
        active = config.getBoolean(ConfPaths.MOVING_SURVIVALFLY_VLFREQUENCY_ACTIVE);
        debug = config.getBoolean(ConfPaths.MOVING_SURVIVALFLY_VLFREQUENCY_DEBUG);
        morevls = config.getInt(ConfPaths.MOVING_SURVIVALFLY_VLFREQUENCY_MOREVLS);
        minaddedvls = config.getInt(ConfPaths.MOVING_SURVIVALFLY_VLFREQUENCY_MINADDEDVLS);
        maxtotalvls = config.getInt(ConfPaths.MOVING_SURVIVALFLY_VLFREQUENCY_MAXTOTALVLS);
        movecount = config.getInt(ConfPaths.MOVING_SURVIVALFLY_VLFREQUENCY_MOVECOUNT);
    }
    //public ViolationFrequencyConfig() {
    //    active = true;
    //    debug = true;
    //    morevls = 5;
    //  minaddedvls = 5;
    //  maxtotalvls = 35; 
    //  movecount = 10;
    //}
}
